# Change these first
owner: marchershey # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

# Configuration
skipDeleteIssues: true

sites:

  - name: Home Network
    url: $NAS_URL
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: "This page can't be displayed"
    __dangerous__body_degraded: "the page you are looking for is not found"
    # icon: https://i.imgur.com/J3CpIgL.png

  - name: Plex Server
    url: $PLEX_URL
    maxResponseTime: 5000
    expectedStatusCodes:
      - 401
    __dangerous__body_down_if_text_missing: "401 Unauthorized"
    __dangerous__body_degraded: "the page you are looking for is not found"
    # icon: https://i.imgur.com/ZhsVi8z.png

  - name: Request App
    url: $REQUEST_URL
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: "Sign In - Overseerr"
    __dangerous__body_degraded: "the page you are looking for is not found"
    # icon: https://i.imgur.com/4vmoxzS.png

  - name: Radarr
    url: $RADARR_URL
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: "SIGN IN TO CONTINUE"
    __dangerous__body_degraded: "the page you are looking for is not found"
    # icon: 

  - name: Sonarr
    url: $SONARR_URL
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: "SIGN IN TO CONTINUE"
    __dangerous__body_degraded: "the page you are looking for is not found"
    # icon: 

  - name: Download Server
    url: $DOWNLOADER_URL
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: "Log in"
    __dangerous__body_degraded: "the page you are looking for is not found"
    # icon: 

  - name: Plex Watcher
    url: $PLEXSTATS_URL
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: "Sign In with Tautulli"
    __dangerous__body_degraded: "the page you are looking for is not found"
    # icon: 

  - name: Meal Server
    url: $MEALS_URL
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: "Loading..."
    __dangerous__body_degraded: "the page you are looking for is not found"
    # icon: 

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.hershey.co
  # baseUrl: /your-repo-name
  logoUrl: https://i.imgur.com/pLVmKmH.png
  name: Marc's Status Page
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
