# Change these first
owner: marchershey # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:

  # # Home Network
  # - name: Home Network
  #   url: $HOME
  #   maxResponseTime: 5000
  #   expectedStatusCodes:
  #   - 200

  # # Plex Server
  # - name: Plex Server
  #   url: $PLEX
  #   headers:
  #     - "Content-Type: application/json"
  #     - "X-Plex-Token: $PLEX_TOKEN"
  #   maxResponseTime: 5000
  #   expectedStatusCodes:
  #   - 200
  
  # Request App
  - name: Request App
    url: $REQUEST
    maxResponseTime: 5000
    expectedStatusCodes:
    - 200

  # MEALS
  - name: Meals Database
    url: $MEALS
    maxResponseTime: 5000
    expectedStatusCodes:
    - 200

  # # Plex Watcher
  # - name: Plex Watcher
  #   url: $STATS
  #   maxResponseTime: 5000
  #   expectedStatusCodes:
  #   - 200

  # # Series Backend
  # - name: Series Backend
  #   url: $SERIES
  #   maxResponseTime: 5000
  #   expectedStatusCodes:
  #   - 200

  # # Movies Backend
  # - name: Movies Backend
  #   url: $MOVIES
  #   maxResponseTime: 5000
  #   expectedStatusCodes:
  #   - 200

  # # Downloader
  # - name: Media Downloader
  #   url: $DOWNLOADER
  #   maxResponseTime: 5000
  #   expectedStatusCodes:
  #   - 200

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.hershey.co
  # baseUrl: /your-repo-name
  logoUrl: https://i.imgur.com/pLVmKmH.png
  name: Marc's Status Page
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
